services:
  - type: worker
    name: udemypy-scraper
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python start_bot.py
    plan: free
    envVars:
      - key: DATABASE
        value: mysql
      - key: DATABASE_URL
        value: mysql://root:@127.0.0.1:3308/tg_enroll
      - key: PAGES_TO_SCRAPE
        value: 1
      - key: FAST_MODE
        value: true
      - key: MAX_COURSES_TO_PROCESS
        value: 3
      - key: MAX_COURSES_TO_SEND
        value: 5
      - key: PYTHONUNBUFFERED
        value: 1 