services:
  - type: web
    name: udemypy-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_server.py
    envVars:
      - key: DATABASE
        value: sqlite3
      - key: TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_LINK
        sync: false
      - key: PAGES_TO_SCRAPE
        value: 2
      - key: MAX_COURSES_TO_SEND
        value: 5 